### ISSUE TITLE
How to maintain a consistent result?

### ISSUE THREAD

**Issue by boom85423** [kingfengji/gcForest#57]
Hello @kingfengji:

Our all think the gcforest performance is awesome.
I already use random_state at config and train test split, but the result is still not consistent.
Actually, I don't know what is the random_state in config stand for random_state in Classifier or K-fold validation in convergence?
Excuse me, what I have missed?

Best regards

**Comment by raven4752** [comment]
I meet the same problem and fix it.  The inconsistency is caused by lib/gcforest/cascade/cascade_classifier.py line 110:
 `            random_state = (self.random_state + hash("[estimator] {}".format(est_name))) % 1000000007
`
the **hash** function give inconsistent results after Python 3.3.
The explanation can be found here: https://stackoverflow.com/questions/27522626/hash-function-in-python-3-3-returns-different-results-between-sessions
I fix that by setting environment variable PYTHONHASHSEED=1 before running my script.

**Comment by boom85423** [comment]
Dear @raven4752:

My problem has solved.
Thanks you very much.

Have a nice day~
